### ISSUE TITLE
Rosetta API dockerfile not running correctly

### ISSUE THREAD

**Issue by HelloKashif** [neo-ngd/neo-common-plugins#1]
https://github.com/neo-ngd/neo-common-plugins/blob/master/RosettaAPI/Dockerfile
This dockerfile just doesn't work.

Steps:
  docker build -t neo .
  docker run neo  <- missing dotnet sdk error + more after fixing that

**Comment by steven1227** [comment]
> https://github.com/neo-ngd/neo-common-plugins/blob/master/RosettaAPI/Dockerfile
> This dockerfile just doesn't work.
> 
> Steps:
> docker build -t neo .
> docker run neo <- missing dotnet sdk error + more after fixing that

Will fix it soon.

**Comment by joeqian10** [comment]
@HelloKashif Hi, please take a look at the new readme file: https://github.com/neo-ngd/neo-common-plugins/blob/master/RosettaAPI/README.md and try again.

**Comment by HelloKashif** [comment]
@joeqian10 thanks a lot. I tested this and it works perfectly.

Closing this issue
